behaviors:
  SpotMicroBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512               
      buffer_size: 5120             
      learning_rate_schedule: linear
      learning_rate: 1e-4          
      beta: 0.0065                    
      beta_schedule: linear
      epsilon: 0.20                  
      epsilon_schedule: linear
      lambd: 0.95                     
      num_epoch: 5                   
      shared_critic: False           
    network_settings:
      num_layers: 2                  
      hidden_units: 256              
      normalize: True                
      #memory:
      #  memory_size: 256             
      #  sequence_length: 16          
    reward_signals:
      extrinsic:
        gamma: 0.99                  
        strength: 1
        network_settings:
          hidden_units: 256          
          num_layers: 2
          normalize: True
      #curiosity:
        #strength: 0.002
        #gamma: 0.82
        #learning_rate: 3e-4
        #network_settings:
          #hidden_units: 256          
          #num_layers: 2
          #normalize: True
    #init_path: "results/Baseline/SpotMicroBehavior/SpotMicroBehavior-2349958.pt"
    time_horizon: 512               
    summary_freq: 50000             
    checkpoint_interval: 50000      
    max_steps: 10000000000    